name: Build Executables

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install pyinstaller requests psutil beautifulsoup4

      - name: Build Executable
        run: |
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            pyinstaller --onefile --console Tracker.py
            fpm -s dir -t deb -n kala-network-tracker -v 1.0 dist/Tracker=/usr/bin/kala-tracker
          elif [[ "${{ runner.os }}" == "Windows" ]]; then
            pyinstaller --onefile --console Tracker.py
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            pyinstaller --onefile --console Tracker.py
          fi

      - name: Upload Executable
        uses: actions/upload-artifact@v3
        with:
          name: Tracker-${{ runner.os }}
          path: |
            dist/Tracker*
            kala-network-tracker_*.deb
